### PR TITLE
Remove AlertType in Plugin Response

### PR DESCRIPTION
**Pull request by xellos00**
Remove AlertType in Plugin Response

- Related: https://github.com/dsrvlabs/vatz/issues/499

### CODE REVIEW

**Review by heejin-github — APPROVED** [review]
LGTM

**Review by rootwarp — COMMENTED** [review]
afaik, this could break backward compatibility between VATZ and plugins because the message format is changed.

you can use "deprecated" option.

https://protobuf.dev/programming-guides/proto3/#options

**Comment by xellos00** [comment]
> afaik, this could break backward compatibility between VATZ and plugins because the message format is changed.
> 
> you can use "deprecated" option.
> 
> https://protobuf.dev/programming-guides/proto3/#options

Yeah, agree!!

**Review by rootwarp — APPROVED** [review]
LGTM

**Pull request merged**
